[package]
name = "include_texture_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
litrs = { version = "0.4.1", default-features = false }
quote = "1.0.33"
